version: "3"
services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "3500:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

networks:
  postgres:
    driver: bridge
