version: "3.8"
services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./.docker/redis:/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    env_file:
      - .env
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    env_file:
      - .env
    environment:
      - DB_HOST="postgres"
      - DB_PORT="5432"
    ports:
      - "3000:3000"
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
