version: '3.8'
services:
  postgres:
    image: postgres:15.1
    container_name: wl-postgres
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - general
  redis:
    image: redis:alpine
    container_name: wl-redis
    volumes:
      - ./.docker/redis:/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    env_file:
      - .env
    networks:
      - general
  redis-commander:
    container_name: wl-redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    networks:
      - general
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - general
    env_file:
      - .env
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    env_file:
      - .env
    networks:
      - general
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    env_file:
      - .env
    networks:
      - general

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  general:
    driver: bridge
