version: "3.8"
services:
  postgres:
    image: postgres:15.1
    networks:
      - api_net
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - api_net
    ports:
      - "3500:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
    ports:
      - "3000:3000"
    networks:
      - api_net
    depends_on:
      - postgres

networks:
  api_net:
    driver: bridge
